language: go
go:
- 1.7
notifications:
  slack:
    secure: SdzK90ML9S/fqSupgfdzL/VrSSEUG+eMvXQwcy48CC/a2Ommz4jWF4Uc6ZAuCSMQIJ6tN7ihML3f0QlAGx8vcispXNBGf5USfJ9tIRi6V2PJGOrHXLTlPr7vEpVCf4vZf4kqAUEEGiFg3DCAooKqtDsLLlpS7mRse8wWxNSvkIvKqHYzPYT2uA2nalEWVxDW//iFzhzV9nViOliRQjx442RmNAm7x2I8XVnDbOB+GbK5VF6oFWYv6TnR84OxyHIu9lwYeD30ydQ4kfRj8hwNz1QUYrWhH9CBJMv8bD+BI4N4wk2qOKl55XwHHFik/TtE6NlSdriYYzvkFpZNT7k8JEM/vo5E/0Rp2A6zaQmlUA68m7c6TOG7nOMNT1K/jbGcDuZjShEEvJywmFA0dvC8Dc2IYHogUrQIGCKpVEG+OVaNJOiQIBVpHB+1eY22ErWDXam2qmrrT+vpj/mLolDLXlswc5zjMVOrg2Klu+x18SxH36RW2GiG+WjYJ1zoSeJAn82AJxuONsxkEhM/tfHJmYTlYnOQLldApbmO6QWCU6PITdIqbGzolSeGoRgt7yK7rsPzVtNbHli9OL/36ebr54KTzqlAAU6fl1kycoVXG4abHL8tL6dbXoFxNrBNOzTf10UcQVfP9zagpWeC6oM/BYiKD8WukyDkGY6RKbR1JNc=
